package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildSteps.DotnetTestStep
import jetbrains.buildServer.configs.kotlin.buildSteps.dotnetBuild
import jetbrains.buildServer.configs.kotlin.buildSteps.dotnetPack
import jetbrains.buildServer.configs.kotlin.buildSteps.dotnetTest
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'BuildClassLib'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("BuildClassLib")) {
    expectSteps {
        dotnetBuild {
            name = "dotnet build"
            projects = "src/TestTeamCity.ClassLib/TestTeamCity.ClassLib.csproj"
            configuration = "Release"
        }
        dotnetTest {
            name = "dotnet test"
            projects = "test/TestTeamCity.ClassLib.Tests/TestTeamCity.ClassLib.Tests.csproj"
            configuration = "Release"
            coverage = dotcover {
                assemblyFilters = "+:TestTeamCity.ClassLib"
            }
        }
        dotnetPack {
            name = "dotnet pack"
            projects = "src/TestTeamCity.ClassLib/TestTeamCity.ClassLib.csproj"
            configuration = "Release"
            args = "--no-build"
        }
    }
    steps {
        update<DotnetTestStep>(1) {
            clearConditions()
            coverage = dotcover {
                toolPath = "%teamcity.tool.JetBrains.dotCover.CommandLineTools.bundled%"
                assemblyFilters = "+:TestTeamCity.ClassLib"
                attributeFilters = ""
                args = ""
            }
        }
    }
}
